### ISSUE TITLE
Volume goes up at media_player.volume_down

### ISSUE THREAD

**Issue by balk77** [B5r1oJ0A9G/teufel_raumfeld#54] opened 2023-09-12 21:03 UTC
Hi, it seems that volume is going up at media_player.volume_down instead of down. Could this be the issue? First `DEFAULT_CHANGE_STEP_VOLUME_DOWN` is set to `-2` and subsequently it is multiplied with `-1`, rendering a positive number. Just tested it and it seems to work when the `-1` is removed.

https://github.com/B5r1oJ0A9G/teufel_raumfeld/blob/8e0f9fbdbf762b84f9406de881c539fde00cd927/custom_components/teufel_raumfeld/const.py#L6

https://github.com/B5r1oJ0A9G/teufel_raumfeld/blob/8e0f9fbdbf762b84f9406de881c539fde00cd927/custom_components/teufel_raumfeld/media_player.py#L647

**Comment by B5r1oJ0A9G** [comment] 2023-09-15 17:30
Hi, maybe this is a duplicate of #52 which is fixed in the current master branch. Can you please check with the master branch and report back if it can be repruduced there?

**Comment by gormed** [comment] 2024-02-03 18:27
I am using version [v0.1.15-alpha3](https://github.com/B5r1oJ0A9G), installed via HACS and I have the same issue (using the media control component).

**Comment by B5r1oJ0A9G** [comment] 2024-07-07 09:48
Menionted fix of #52 is now released with version 0.1.16-alpha1. On my side I could not reproduce the error. Can you please check whether the problem still exists with 0.1.16-alpha1?

**Comment by mathebox** [comment] 2024-09-08 18:36
I did run into this bug using version  0.1.16-alpha1. So I also took a look at the code.  

As it turns out, removing the multiplication with `-1` as suggested above will not provide an adequate fix for this issue. This only works in combination with a negative value for `OPTION_CHANGE_STEP_VOLUME_DOWN`. As soon as you change the step value in the config panel of the integration, this will be a positive integer ([enforced by the config flow](https://github.com/B5r1oJ0A9G/teufel_raumfeld/blob/master/custom_components/teufel_raumfeld/config_flow.py#L96-L102)) and you can't reproduce the bug anymore.

Hence, the value of `DEFAULT_CHANGE_STEP_VOLUME_DOWN` should be adjusted. I will prepare a PR 😉

**Closed** 2024-09-29 19:10 UTC
Labels: bug
