### ISSUE TITLE
No media entity is created

### ISSUE THREAD

**Issue by JimboJones3101** [B5r1oJ0A9G/teufel_raumfeld#64] opened 2024-06-18 06:35 UTC
Hi there,

seemingly I am suffering from the same issue as [here](https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/44).

I was using this component frequently the last weeks, when all of a sudden it stopped working. I checked HA didnt find nothing, redownloaded the component and reconfigured and figured out that my host is recognised. 2 Devices are recognised (seems correct as I have an Teufel S and Teufel M) but only 6 entities are created. Per device this is :

Powerstate
Softwareversion
Updateinfoversion
No media entity is created, no zone no nothing. I enabled logging and this is the error I'm getting when reloading the integration:

`Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:366
integration: Media player (documentation, issues)
First occurred: 08:30:20 (1 occurrences)
Last logged: 08:30:20

Error while setting up teufel_raumfeld platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/teufel_raumfeld/media_player.py", line 148, in async_setup_entry
    entity_registry = hass.helpers.entity_registry.async_get(hass)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given
`

I tried to reproduce the solution but the code seems fixed from back in the days, furthermore the errormessage is different this time.

anybody an idea of how to fix this?

thanks in advance

**Comment by 4711Raven** [comment] 2024-06-18 18:40
I noticed the same issue after update to Homassistant core 2024.6  with 2024.5.x all was working fine. I am running HA on a VM and have reverted to version 2024.5.

**Comment by greentux** [comment] 2024-06-19 15:48
But this cant be the solution...

**Comment by zwerg1395** [comment] 2024-06-21 06:49
> Hi there,
> 
> seemingly I am suffering from the same issue as [here](https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/44).
> 
> I was using this component frequently the last weeks, when all of a sudden it stopped working. I checked HA didnt find nothing, redownloaded the component and reconfigured and figured out that my host is recognised. 2 Devices are recognised (seems correct as I have an Teufel S and Teufel M) but only 6 entities are created. Per device this is :
> 
> Powerstate Softwareversion Updateinfoversion No media entity is created, no zone no nothing. I enabled logging and this is the error I'm getting when reloading the integration:
> 
> `Logger: homeassistant.components.media_player Source: helpers/entity_platform.py:366 integration: Media player (documentation, issues) First occurred: 08:30:20 (1 occurrences) Last logged: 08:30:20
> 
> Error while setting up teufel_raumfeld platform for media_player Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform await asyncio.shield(awaitable) File "/config/custom_components/teufel_raumfeld/media_player.py", line 148, in async_setup_entry entity_registry = hass.helpers.entity_registry.async_get(hass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: async_get() takes 1 positional argument but 2 were given `
> 
> I tried to reproduce the solution but the code seems fixed from back in the days, furthermore the errormessage is different this time.
> 
> anybody an idea of how to fix this?
> 
> thanks in advance

No that is something else , the issue here seems to be that the home assistant team has already started to phase out the function used and the new way to call the registry needs to be implemented.Saw the same error with other integrations that use this function.

**Comment by cogelito** [comment] 2024-06-26 21:15
> and the new way to call the registry needs to be implemented

Is that something we could change ourselves in one of the .py files or does it need action from the developer?
(Sorry, in case that this is a dumb question, I‘m just an autodidact trying to learn)

**Comment by holli73** [comment] 2024-06-27 23:39
as i was using this as well and tried a lot to get it running - no success - i found a real cool HA intergration -> https://music-assistant.io/integration/ - i use this now and it works great with the RaumFeld speakers - i used the UPnP/DLNA Provider and the HA integration is really good and on my node-red workflows i only needed to change the entity id's...
these are all my RaumFeld Devices:
![image](https://github.com/B5r1oJ0A9G/teufel_raumfeld/assets/1434090/9e1ed8b8-d29a-4493-b241-53f50ce4927b)
and if something is playing it has a real good interface - now i can stream everything from HA to the speakers
![image](https://github.com/B5r1oJ0A9G/teufel_raumfeld/assets/1434090/d52ae9be-02cd-4295-824b-429089b495c9)

**Comment by klausw01** [comment] 2024-06-27 23:49
> > and the new way to call the registry needs to be implemented
> 
> Is that something we could change ourselves in one of the .py files or does it need action from the developer? (Sorry, in case that this is a dumb question, I‘m just an autodidact trying to learn)

See my comment in the other thread.

https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/63#issuecomment-2195798469

Probably this may help you :)

**Comment by B5r1oJ0A9G** [comment] 2024-07-07 09:09
Thanks for reporting this issue.!I assume this to be a duplicate of #63 and close it since the fix from @klausw01 has been merged and released.

**Closed by B5r1oJ0A9G** 2024-07-07 09:09 UTC
Labels: duplicate
